# Site settings
url: https://covidupdates.ca
title: COVID-19 Canadian Government Updates
tag_text: COVID-19 Canadian Government Updates
description: Short & to-the-point updates from the Canadian Government regarding COVID-19

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-target-blank
